export const ATTENDANCE_UPDATE_REQUEST = "ATTENDANCE_UPDATE_REQUEST";
export const ATTENDANCE_UPDATE_SUCCESS = "ATTENDANCE_UPDATE_SUCCESS";
export const ATTENDANCE_UPDATE_FAIL = "ATTENDANCE_UPDATE_FAIL";