export const HOUR_LIST_REQUEST = "HOUR_LIST_REQUEST";
export const HOUR_LIST_SUCCESS = "HOUR_LIST_SUCCESS";
export const HOUR_LIST_FAIL = "HOUR_LIST_FAIL";

export const HOUR_DETAILS_REQUEST = "HOUR_DETAILS_REQUEST";
export const HOUR_DETAILS_SUCCESS = "HOUR_DETAILS_SUCCESS";
export const HOUR_DETAILS_FAIL = "HOUR_DETAILS_FAIL";

export const HOUR_CREATE_REQUEST = "HOUR_CREATE_REQUEST";
export const HOUR_CREATE_SUCCESS = "HOUR_CREATE_SUCCESS";
export const HOUR_CREATE_FAIL = "HOUR_CREATE_FAIL";
export const HOUR_CREATE_RESET = "HOUR_CREATE_RESET";

export const HOUR_DELETE_REQUEST = "HOUR_DELETE_REQUEST";
export const HOUR_DELETE_SUCCESS = "HOUR_DELETE_SUCCESS";
export const HOUR_DELETE_FAIL = "HOUR_DELETE_FAIL";
export const HOUR_DELETE_RESET = "HOUR_DELETE_RESET";