export const STUDENT_CREATE_REQUEST = "STUDENT_CREATE_REQUEST";
export const STUDENT_CREATE_SUCCESS = "STUDENT_CREATE_SUCCESS";
export const STUDENT_CREATE_FAIL = "STUDENT_CREATE_FAIL";
export const STUDENT_CREATE_RESET = "STUDENT_CREATE_RESET";

export const STUDENT_DETAILS_REQUEST = "STUDENT_DETAILS_REQUEST";
export const STUDENT_DETAILS_SUCCESS = "STUDENT_DETAILS_SUCCESS";
export const STUDENT_DETAILS_FAIL = "STUDENT_DETAILS_FAIL";

